### PR TITLE
matching tangram-es glsl fix for globals init

### PR DESCRIPTION
**Pull request by patriciogonzalezvivo**
Matching @blair1618 fix of glsl global init bug https://github.com/tangrams/tangram-es/commit/63120ab16910ea7dfd91dbb1c2374f0b0699f5c7#commitcomment-14197819

### CODE REVIEW

**Comment by bcamper** [comment]
Tests are failing with GLSL errors on material uniforms, have you verified this locally? It may be caused by certain scenarios.

https://circleci.com/gh/tangrams/tangram/1952

**Comment by patriciogonzalezvivo** [comment]
I did. I did a make lint and run a local python server to see if everything was looking right

**Comment by bcamper** [comment]
But it looks like there are problems when you use these uniforms in styles.
Can you try with material blocks?

**Comment by patriciogonzalezvivo** [comment]
Trying gotham.yaml (https://github.com/tangrams/tangram-sandbox/blob/gh-pages/styles/gotham.yaml). Seams fine.

screen shot 2015-11-05 at 1 05 47 pm

Lint produce no errors
screen shot 2015-11-05 at 1 09 11 pm

**Comment by bcamper** [comment]
Hmm, could be a test error, I'll dig in.

**Comment by bcamper** [comment]
The test accurately shows that remotely loaded styles are broken, e.g.:

`scene.load('https://raw.githubusercontent.com/tangrams/eraser-map/gh-pages/eraser-map.yaml')`

Need to investigate why. Something is wrong with light/material injection in that case.

**Comment by patriciogonzalezvivo** [comment]
I was looking at eraser-map running with this changes... looks fine too : /

screen shot 2015-11-05 at 3 49 21 pm

Just a couple of icons not found:

```
MPZN ZoomControl: Conditional zoom control active.
zoom-control.js:32 MPZN ZoomControl: No touchscreen detected, exiting.
module.js:91 Tangram v0.3.3: Scene.makeWorkers: initializing worker 0
module.js:91 Tangram v0.3.3: Scene.makeWorkers: initializing worker 1
module.js:91 Tangram v0.3.3: Scene.makeWorkers: initialized worker 0
module.js:91 Tangram v0.3.3: Scene.makeWorkers: initialized worker 1
module.js:91 Tangram v0.3.3: Vertex Array Object extension available
2module.js:91 Tangram v0.3.3: StyleManager.compile(): compiled all styles
module.js:91 Tangram v0.3.3: Scene: build geometry finished
module.js:91 Tangram v0.3.3: Scene: rendered 0 primitives (0 features in selection map)
module.js:91 Tangram v0.3.3: worker 0: updated config
2module.js:91 Tangram v0.3.3: worker 1: updated config
module.js:91 Tangram v0.3.3: worker 0: updated config
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9646/12319/15: [  {"network":81,"response_size":13410,"parsing":3,"rendering":19,"features":133,"geometries":1316,"buffer_size":94080,"geom_ratio":"9.9"} ]
points.js:89 Style: in style 'icons', could not find sprite 'residential' for texture 'pois'
points.js:89 Style: in style 'icons', could not find sprite 'footway' for texture 'pois'
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9645/12321/15: [  {"network":133,"response_size":5189,"parsing":1,"rendering":1,"features":17,"geometries":145,"buffer_size":10392,"geom_ratio":"8.5"} ]
points.js:89 Style: in style 'icons', could not find sprite 'residential' for texture 'pois'
points.js:89 Style: in style 'icons', could not find sprite 'pitch' for texture 'pois'
points.js:89 Style: in style 'icons', could not find sprite 'residential' for texture 'pois'
4points.js:89 Style: in style 'icons', could not find sprite 'residential' for texture 'pois'
points.js:89 Style: in style 'icons', could not find sprite 'wood' for texture 'pois'
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9644/12322/15: [  {"network":275,"response_size":9263,"parsing":1,"rendering":2,"features":63,"geometries":1108,"buffer_size":80340,"geom_ratio":"17.6"} ]
points.js:89 Style: in style 'icons', could not find sprite 'pitch' for texture 'pois'
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9646/12320/15: [  {"network":24,"response_size":23440,"parsing":13,"rendering":54,"features":283,"geometries":3891,"buffer_size":277344,"geom_ratio":"13.7"} ]
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9645/12320/15: [  {"network":98,"response_size":9138,"parsing":2,"rendering":10,"features":104,"geometries":1437,"buffer_size":102576,"geom_ratio":"13.8"} ]
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9648/12321/15: [  {"network":110,"response_size":27736,"parsing":3,"rendering":27,"features":227,"geometries":2873,"buffer_size":202152,"geom_ratio":"12.7"} ]
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9650/12320/15: [  {"network":141,"response_size":11537,"parsing":1,"rendering":10,"features":135,"geometries":2346,"buffer_size":162852,"geom_ratio":"17.4"} ]
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9644/12319/15: [  {"network":153,"response_size":18859,"parsing":2,"rendering":17,"features":229,"geometries":1570,"buffer_size":113340,"geom_ratio":"6.9"} ]
module.js:91 Tangram v0.3.3: Tile: debug for osm/15/9650/12321/15: [  {"network":172,"response_size":20862,"parsing":3,"rendering":13,"features":194,"geometries":2662,"buffer_size":187788,"geom_ratio":"13.7"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9647/12319/15: [  {"network":189,"response_size":59431,"parsing":5,"rendering":28,"features":640,"geometries":7325,"buffer_size":517896,"geom_ratio":"11.4"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9647/12320/15: [  {"network":224,"response_size":88251,"parsing":6,"rendering":35,"features":1046,"geometries":12236,"buffer_size":874668,"geom_ratio":"11.7"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9650/12322/15: [  {"network":280,"response_size":51291,"parsing":6,"rendering":17,"features":378,"geometries":5265,"buffer_size":372300,"geom_ratio":"13.9"} ]
2points.js:89 Style: in style 'icons', could not find sprite 'meadow' for texture 'pois'
points.js:89 Style: in style 'icons', could not find sprite 'pitch' for texture 'pois'
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Scene: rendered 42174 primitives (4135 features in selection map)
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9645/12322/15: [  {"network":408,"response_size":4793,"parsing":1,"rendering":1,"features":16,"geometries":56,"buffer_size":3960,"geom_ratio":"3.5"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9646/12321/15: [  {"network":25,"response_size":11823,"parsing":11,"rendering":41,"features":112,"geometries":1284,"buffer_size":90396,"geom_ratio":"11.5"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Scene: rendered 42230 primitives (4521 features in selection map)
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9649/12320/15: [  {"network":104,"response_size":22694,"parsing":3,"rendering":27,"features":206,"geometries":2714,"buffer_size":190284,"geom_ratio":"13.2"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9645/12319/15: [  {"network":136,"response_size":10800,"parsing":0,"rendering":12,"features":143,"geometries":1513,"buffer_size":109272,"geom_ratio":"10.6"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9644/12320/15: [  {"network":149,"response_size":11706,"parsing":0,"rendering":10,"features":173,"geometries":2077,"buffer_size":147132,"geom_ratio":"12.0"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9644/12321/15: [  {"network":160,"response_size":9532,"parsing":1,"rendering":8,"features":84,"geometries":1505,"buffer_size":108300,"geom_ratio":"17.9"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9650/12319/15: [  {"network":169,"response_size":29480,"parsing":1,"rendering":21,"features":343,"geometries":4615,"buffer_size":322944,"geom_ratio":"13.5"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9647/12321/15: [  {"network":195,"response_size":35254,"parsing":2,"rendering":17,"features":396,"geometries":4938,"buffer_size":351612,"geom_ratio":"12.5"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9648/12320/15: [  {"network":214,"response_size":48727,"parsing":3,"rendering":18,"features":471,"geometries":5875,"buffer_size":423828,"geom_ratio":"12.5"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9649/12321/15: [  {"network":236,"response_size":42671,"parsing":3,"rendering":23,"features":569,"geometries":5392,"buffer_size":384072,"geom_ratio":"9.5"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9648/12319/15: [  {"network":264,"response_size":82908,"parsing":4,"rendering":22,"features":656,"geometries":7827,"buffer_size":554652,"geom_ratio":"11.9"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9649/12319/15: [  {"network":292,"response_size":71740,"parsing":8,"rendering":37,"features":463,"geometries":5392,"buffer_size":379644,"geom_ratio":"11.6"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9647/12322/15: [  {"network":341,"response_size":8697,"parsing":3,"rendering":4,"features":86,"geometries":1125,"buffer_size":79356,"geom_ratio":"13.1"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9646/12322/15: [  {"network":348,"response_size":10076,"parsing":1,"rendering":9,"features":139,"geometries":1379,"buffer_size":99120,"geom_ratio":"9.9"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9649/12322/15: [  {"network":365,"response_size":50921,"parsing":8,"rendering":32,"features":558,"geometries":5790,"buffer_size":415668,"geom_ratio":"10.4"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Tile: debug for osm/15/9648/12322/15: [  {"network":411,"response_size":62203,"parsing":5,"rendering":11,"features":285,"geometries":3526,"buffer_size":247320,"geom_ratio":"12.4"} ]
:8000/dist/tangram.debug.js:28448 Tangram v0.3.3: Scene: rendered 97182 primitives (4521 features in selection map)
module.js:91 Tangram v0.3.3: Scene: rendered 78933 primitives (4521 features in selection map)
```

**Comment by bcamper** [comment]
Nope, see my comment, it is when you load a scene after initial load. That is what the test is for.

**Comment by patriciogonzalezvivo** [comment]
I don't understand what you mean.

**Comment by patriciogonzalezvivo** [comment]
Maybe is not cleaning the previous blocks of "setup"

**Comment by bcamper** [comment]
Please check the test log for more info. Load the scene, then run this command:

`scene.load('https://raw.githubusercontent.com/tangrams/eraser-map/gh-pages/eraser-map.yaml')`

It will fail...

**Comment by bcamper** [comment]
This was failing because the material and lighting systems expected to be able to fully replace their respective shader blocks when styles are rebuilt. This doesn't work when they are also injecting into a general injection point that might also be getting blocks from other sources. I was able to fix this by moving some re-init code around to ensure all shader blocks are reset.

Another alternative I had working was to separate out the `setup` block so that material and lights each had their own main injections, `material-main` and `lighting-main`:
https://github.com/tangrams/tangram/commit/90d619df6bb014723517c4a025d143cdbc14391a

That said, I think this solution is probably simpler and more inline with ES anyway.

**Comment by bcamper** [comment]
@blair1618 do we have a device in the office we can test this with? I'd like to do so before merging.

**Comment by blair1618** [comment]
We tested on a Galaxy Note 4 Edge (I think that's the name) that Diana
brought in.

**Comment by bcamper** [comment]
Verified the issue and the fix on the Samsung Galaxy Note Edge.

**Comment by patriciogonzalezvivo** [comment]
:clap: :clap: :+1:

**Pull request merged**
