### PR TITLE
Labels v2

### PR DESCRIPTION
**Pull request by karimnaaji**
Improvements on labels, splitted in several classes now. Some new features accessible from the stylesheet:
- stroke width
- font weight / font style
- capitalization

Other features:
- retina display fonts
- text label replacement
- line wrapping (point labels)

Some new kind of labels:
- multi-line, multi-polygon, polygon, multi-point

Priorities:
- numeric label priorities can be given from the stylesheet
- ordering polygon labels by area size.

Last todos for tangram v1: point label positioning

### CODE REVIEW

**Comment by bcamper** [comment]
@karimnaaji I updated this with master, looking good :)

**Comment by bcamper** [comment]
Retina label culling seems much better now.

**Comment by bcamper** [comment]
@karimnaaji can you take care of lint :)

**Comment by karimnaaji** [comment]
Nice! Taking care of lint

**Pull request merged**
