### PR TITLE
Split Arabic text for curved labels

### PR DESCRIPTION
**Pull request by mapmeld**
Let's do this (Arabic, Hebrew, and Divehi (Maldives) labels)

In Arabic text, some letters join to the left, and others don't. (Australia =  أستراليا for a reference). These letters are common and consistent, so we can reliably split a word on them without splitting the baseline. The only additional concern is making sure that any vowel-marks for the letter don't get split off and put at the start of the next segment. 

TODO on this: bidirectional / bilingual text. Potentially replacing with a good RegEx if we can find it

Hebrew and Divehi won't use this splitter - instead I'm just adding their vowel-marks to the code from last curved labels code

### CODE REVIEW

**Comment by bcamper** [comment]
Awesome! Two issues I am seeing so far:

1. The Arabic code path isn't being triggered for some strings. An example is "شارع أحمد باشا كمال". It looks like the line start and end (`^` and `$`) symbols in `arabic_range` are causing it to only match strings that are *single Arabic words* (no spaces, neutral chars, etc.). We only need to know if there are *any* Arabic chars in the string (bidi detection is done earlier in the flow and currently skips `splitLabelText()` entirely), so I believe that just `/[\u0600-\u06FF]+/` should work fine.

I noticed this because this string the last (first RTL) character in the circled word is incorrect (this is the result of it going down the regular grapheme cluster path):
screen shot 2017-05-31 at 10 23 18 am

2. When I updated the regex to not remove line start/end matches, it looks like that problem is fixed, however a new problem is introduced:
screen shot 2017-05-31 at 11 13 05 am

I believe what we're seeing here is a new manifestation of a previously fixed issue for RTL text (#541). When the text segment starts or ends with a neutral character (space or otherwise), it gets flipped to the wrong side during Canvas text rendering, making it join to the wrong word. You can see this in the circled word above, and also in the word from the first example too (leftmost character in the string incorrectly has a space after it). 

The current code to fix this issue (for Hebrew) is [here](https://github.com/mapmeld/tangram/blob/92c2bb9f9d118c758edd49cfb4650e7de5ee0167/src/styles/text/canvas_text.js#L676-L705), but it's being skipped in the new Arabic path (which builds the segments a bit differently). The neutral char code fix still feels sort of clunky to me, it would be ideal to factor it out and have a common implementation for all RTL text.

**Comment by bcamper** [comment]
@mapmeld I have a fix to deal with the second issue above, which also allows us to remove the existing special-case code for it. Will push it today or tomorrow.

**Comment by bcamper** [comment]
@mapmeld I've pushed a few changes here, extending your branch: https://github.com/tangrams/tangram/compare/mapmeld-curvy-labels

This revamps a bit of how we handle RTL and neutral characters to avoid the issue I mentioned above. It also slightly changes your Arabic regex to handle strings with spaces or other neutral chars.

Things look good for the places where I'd previously seen issues, but I haven't tested extensively yet.

**Comment by mapmeld** [comment]
I'm not familiar with how the old RTL code was working exactly, but if you feel good about this, this could be the way to do it

Does it flip any text if you have bidirectional label (Latin + Arabic)?

**Comment by bcamper** [comment]
I'm fairly confident this is working (as much as I can be from visual inspection as a non-reader anyway!) for Arabic.

For your bidi question, we still explicitly blacklist bidi text from curving (for now):
https://github.com/tangrams/tangram/compare/mapmeld-curvy-labels#diff-56e91e9082620f32a1ac931d75dc9957R71

So anything that either has bidi, or characters with unsupported curved shaping (only Mongolian now!) will skip curving, but still render as a straight label.

Going to merge this, then apply my additional changes on top. Thanks again!!

**Comment by bcamper** [comment]
See follow-up work in:
https://github.com/tangrams/tangram/commit/0ce6c045e0962f9996fcbde5b68b8bf59ce6a622
https://github.com/tangrams/tangram/commit/a114f98115a5276008b73749e2c6eda33ec88fba
https://github.com/tangrams/tangram/commit/02f1de28153bd0bd0a591b5e0dfa28a07b85cf64

**Comment by mapmeld** [comment]
thanks for making it happen! 👍

**Comment by bcamper** [comment]
Released in [v0.13.0](https://github.com/tangrams/tangram/releases/tag/v0.13.0)

**Pull request merged**
