### PR TITLE
Label/Sprite offsets

### PR DESCRIPTION
**Pull request by karimnaaji**
Give the ability to offset sprite icons and labels,
- add a vertex attribute to the point style (offset in pixel applied directly in screen space)
- the following options are now availble from the stylesheet:
```yaml
draw:
    icons:
        # applies an offset of 13 pixels up along y-axis
        offset: [0px, 13px] 
[...]
draw:
    text:
        # applies an offset of 13 pixels down along y-axis
        offset: [0px, -13px]
```
- quick refactor on how features are stored in the text style

### CODE REVIEW

**Comment by bcamper** [comment]
Can we flip the Y axis so positive offset is down? :) Since it's the default coordinate system for the browser/CSS, etc.

https://twitter.com/ID_AA_Carmack/status/633426212304646144

**Comment by karimnaaji** [comment]
Oh yes, and it would also match with the native version! Let's get closer 1.0

**Comment by bcamper** [comment]
Seems like it's still behaving as y pointing up... maybe it got double-flipped?

**Comment by karimnaaji** [comment]
I just checked and it's working for me. Can you double check?

**Pull request merged**
