### PR TITLE
Support for non-tiled GeoJSON and TopoJSON sources

### PR DESCRIPTION
**Pull request by bcamper**
This adds support for non-tiled, standalone GeoJSON and TopoJSON sources, by using the excellent [geojson-vt](https://github.com/mapbox/geojson-vt) library to cut these into tiles (appropriately simplified per zoom level) on the fly, client-side. This makes it much easier to use arbitrary data with Tangram!

In addition, the name and function of data sources is simplified: instead of having `GeoJSONTiles` and `TopoJSONTiles` source types, these are simplified to `GeoJSON` and `TopoJSON`. When creating the source, the URL is examined to see if it contains a tile template (`{x}`, `{y}`, and `{z}` parameters). If it **does** contain a tile template, a standard tiled data source is created. If the URL does **not** contain a tile template, an client-side-tiling source using `geojson-vt` is automatically created instead.

Example of shortened source type name:

```
    # creates a server-tiled data source (URL tile template is present)
    osm:
        type: GeoJSON
        url:  http://vector.mapzen.com/osm/all/{z}/{x}/{y}.json
    # creates a client-tiled data source (no URL tile template)
    counties:
        type: TopoJSON
        url: https://gist.githubusercontent.com/mbostock/4090846/raw/c899e3d4f3353924e495667c842f54a07090cfab/us.json
```

The bundled demo has been updated to use the shorter, unified source type names, but the older ones still work for backwards compatibility.

Here's a US counties TopoJSON (via one of Mike Bostock's examples), as a non-tiled source:
tangram-1434948396408

### CODE REVIEW

**Comment by bcamper** [comment]
cc @meetar @sensescape @nvkelso out of interest

cc @blair1618 @tallytalwar @patriciogonzalezvivo on backwards compatible "API" change (accepting older `GeoJSONTiles`/`TopoJSONTiles` source names in addition to new unified ones).

**Comment by bcamper** [comment]
@meetar @patriciogonzalezvivo after this is merged, let's update demos and docs to use the unified source type names, though the older ones will continue to work.

**Comment by louh** [comment]
OMG this is huge. :+1: :tada: :open_mouth:

**Comment by meetar** [comment]
@bcamper We're champing at the bit over here, can we merge this?

**Comment by bcamper** [comment]
I want to take a look at a few more things... hold your horses :)

**Comment by meetar** [comment]
:horse_racing: :dash: :checkered_flag: :trophy:

**Comment by bcamper** [comment]
- split data sources into separate files?
- remove Y flipping from internal tile coords?
- open branch/PR to update docs (simplified `GeoJSON`/`TopoJSON` source type naming in addition to non-tiled sources)

**Pull request merged**
