### PR TITLE
bump earcut version

### PR DESCRIPTION
**Pull request by bdon**
I was seeing some sliver polygons being created - was resolved by bumping `earcut` to the latest. also regenerated the package-lock.json

### CODE REVIEW

**Comment by bdon** [comment]
FYI, I'm noticing some new, different triangulation artifacts on this new version - will need to confirm if they were introduced by this change

**Comment by meetar** [comment]
This sounds like a job for

The Differ

**Comment by bdon** [comment]
OK, It looks like the issue I'm seeing is tangram-specific but was not introduced by this PR, so the upgrade should still be good. screenshot and associated PBF:

Screen Shot 2020-06-06 at 12 01 15 PM

[11_1819_828.pbf.zip](https://github.com/tangrams/tangram/files/4739335/11_1819_828.pbf.zip)

**Comment by bcamper** [comment]
Verified with differ (@bdon this may interest you for future use):
- Unit tests: https://tangrams.github.io/differ/?1=https://tangrams.github.io/differ-tests/unit-tests/unittests01.json&2=&lib1=https://unpkg.com/tangram/dist/tangram.min.js&lib2=https://deploy-preview-755--tangram.netlify.app/dist/tangram.min.js&go
- Bubble Wrap: https://tangrams.github.io/differ/?1=https://www.nextzen.org/carto/bubble-wrap-style/bubble-wrap-style.zip&2=&lib1=https://unpkg.com/tangram/dist/tangram.min.js&lib2=https://deploy-preview-755--tangram.netlify.app/dist/tangram.min.js&go

**Pull request merged**
