### PR TITLE
Alpha background

### PR DESCRIPTION
**Pull request by bcamper**
Adds alpha to the Tangram GL canvas, which allows for Leaflet layers (or other HTML content) to be placed *beneath* the map, in addition to on top of it. The GL canvas is now inserted in the correct location in the Leaflet DOM (previously it was pulled out of the DOM to make positioning simpler, and because without alpha it often got covered by other layers). 

This also necessitates a few changes to client interactivity handling, since we want listeners and pop-ups attached to the map container, not the Tangram scene container. (see https://github.com/tangrams/tangram/compare/alpha-background#diff-a2925ce738063617bef38726407de2d0R484, https://github.com/tangrams/tangram/compare/alpha-background#diff-a2925ce738063617bef38726407de2d0R511); cc @meetar and @nvkelso on this point for adjusting other demos (but will put this Tangram change in a 0.4 release for better compatibility transition).

Color values can now include an alpha component (including for "opaque" geometry that isn't otherwise doing GL blending with other Tangram features). For example:

```
scene:
    background:
        color: [0, 0, 0, .5] # allow background to show through with 50% opacity
```

or 

```
scene:
    background:
        color: transparent
```

or

```
        draw:
            polygons:
                color: [.25, 0, 0, .25] # draw red with 25% opacity in background
```

Here's an example of Tangram buildings and roads rendered over Stamen's terrain raster tiles:

screen shot 2015-10-15 at 10 16 47 pm

### CODE REVIEW

**Comment by bcamper** [comment]
Note: I haven't been able to test this on iOS yet, and given that we've seen different premultiplied canvas alpha behavior on iOS vs. desktop Safari -- causing the "dirty" text halos -- I need to make sure to do that before this is merged.

**Comment by blair1618** [comment]
Is `background: color: transparent` equivalent to `background: color: [0, 0, 0, 0]`? If so, why add exceptional behavior? How much do we really like CSS? ;)

**Comment by bcamper** [comment]
It was just an example that works for free because 'transparent' is a CSS
'color' picked up by the parser automatically :) I expect the same is true
in the C++ version.

**Comment by blair1618** [comment]
Ooh I see! Very nice.

**Pull request merged**
