### PR TITLE
Oriented lines

### PR DESCRIPTION
**Pull request by dmvaldman**
This PR addresses https://github.com/tangrams/tangram/issues/471 where we were not previously using the orientation of a line to modify an offset of a label. This allows a line label to remain on a specific side (inside or outside) of a polygon as it is placed around the polygon's boundary.

Currently the offset will follow the geometry orientation only if both an offset is specified and the `text_source` is one of `name:left` or `name:right`. This `text_source` pattern is currently used in our tiles. However, there was a discussion in https://github.com/tangrams/tangram/issues/471 to use a more intentional scene file markup like

```
draw:
  text:
    text_source:
      left: 'name:left'
      right: ‘name:right'
```
This part is not yet implemented. Are we in agreement about this syntax @nvkelso @bcamper?

### CODE REVIEW

**Comment by nvkelso** [comment]
@dmvaldman Can you add a screenshot, please? And example YAML code snippet so I can give it a whirl in Bubble Wrap?

> However, there was a discussion in #471 to use a more intentional scene file markup like

+1 for adding the new text_source `left`, `right` syntax suggested in #471:

```
draw:
  text:
    text_source:
      left: 'name:left'
      right: ‘name:right'
```

**Comment by dmvaldman** [comment]
Check out an example here https://precog.mapzen.com/tangrams/tangram/oriented-lines-example/

**Comment by nvkelso** [comment]
This is super rad! I've tested in the areas mentioned in #471 and they're all looking good.

@dmvaldman and I were talking in Slack about exposing an option to fail the pair of labels if one of them can't be placed (similar to what happens with requiring both sprite and name for points by default, but allowing that to fail optionally).

https://precog.mapzen.com/tangrams/tangram/oriented-lines-example/#40.65394574139022,-74.09729003906251,13

screen shot 2017-03-01 at 13 46 16

**Comment by bcamper** [comment]
Sweet, looking great. I also like extending `text_source` to accept an object with `left` and `right` properties (it currently accepts string and function values, so this is a natural extension). Adding a parameter to optionally require both works for me too (assuming it can be done without introducing a lot of complexity).

**Comment by dmvaldman** [comment]
I'll look at using the point/text linking to make sure both left and right labels appear together.

Otherwise, here's my fav. Who knew Kentucky was an island? :-)

tangram-1488407583324

**Comment by nvkelso** [comment]
Kentucky Bend :)

**Comment by dmvaldman** [comment]
Do we want to support oriented offsets for both markups:

```
draw:
  text:
    text_source:
      left: 'name:left'
    offset : [0, 10px]
```

and 

```
draw:
  text:
    text_source: 'name:left'
  offset : [0, 10px]
```

Or just the former?

**Comment by nvkelso** [comment]
I prefer this one as it isn't tied to the Tilezen implementation of vector tiles, and generally seems a bit more sane anyhow.

```
draw:
  text:
    text_source:
      left: 'name:left'
    offset : [0, 10px]
```

**Pull request closed without merging**
